apiVersion: v1
kind: ConfigMap
metadata:
  name: green-env-vars
data:
  COLOR_PATH: /mnt/config/color.txt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: green-config-vol
data:
  color.txt: green
  hello-from-green.js: |
    console.log("Hello from ")
    console.log("The green config map")
