#for documentation equivalent the command
# kubectl expose pod nginx-pod --type=NodePort --port=80
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
