apiVersion: v1
kind: Pod
metadata:
  name: color-api-pod
  labels:
    app: color-api-pod
spec:
  containers:
    - name: color-api-pod
      image: jim124/color-api:1.2.1
      resources:
        limits:
          memory: '512Mi'
          cpu: '500m'
        requests:
          memory: '510Mi'
          cpu: '500m'
      env:
        - name: DELAY_STARTUP
          value: 'false'
        - name: FAIL_LIVENESS
          value: 'true'
      ports:
        - containerPort: 80
      startupProbe:
        httpGet:
          path: /up
          port: 80
        failureThreshold: 2
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /health
          port: 80
        failureThreshold: 3
        periodSeconds: 10
