apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
  - nginx-dep.yaml
namePrefix: dev-
nameSuffix: -v1
labels:
  - pairs:
      tier: backend
      team: finance
commonAnnotations:
  developer: 'test@example.com'
  repository: 'github.com'
  maintainer: 'test@example.com'
images:
  - name: nginx
    newTag: 1.0.1
replicas:
  - name: nginx
    count: 3
generatorOptions:
  disableNameSuffixHash: false
configMapGenerator:
  - name: feature-flag-config
    literals:
      - use_db=true
      - expose_metrics=true
      - some_other_feature=true

  - name: db-init-config
    files:
      - db-init.js
  - name: local-config
    envs:
      - .env.local
secretGenerator:
  - name: local-config
    envs:
      - .env.local
    type: Opaque
