apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
    key: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      # key: nginx
  template:
    metadata:
      labels:
        app: nginx
        # key: nginx
    spec:
      containers:
        - name: nginx-prod
          image: nginx:1.27.0
          ports:
            - containerPort: 80
