apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
        - name: color-api
          image: jim124/color-api:1.1.0
          ports:
            - containerPort: 80
