apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dep
  labels:
    app: nginx
  annotations:
    'kubernetes.io/change-cause': 'update nginx to tag 1.2'
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx:1.27.1-alpine
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
