apiVersion: v1
kind: Pod
metadata:
  name: color-api
  labels:
    app: color-api
spec:
  containers:
    - name: color-api
      image: jim124/color-api:1.3.0
      envFrom:
        - configMapRef:
            name: red-config-ref
      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
        requests:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 80
