apiVersion: v1
kind: Pod
metadata:
  name: color-api-blue
  labels:
    app: color-api-blue
spec:
  containers:
    - name: color-api
      image: jim124/color-api:1.3.0
      env:
        - name: DEFAULT_COLOR
          valueFrom:
            configMapKeyRef:
              key: COLOR
              name: red-config-key

      resources:
        limits:
          memory: '128Mi'
          cpu: '500m'
        requests:
          memory: '128Mi'
          cpu: '500m'
      ports:
        - containerPort: 80
