apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-1
resources:
  - ../_network-policies
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: mongodb-root-cred
    envs:
      - .env.root-cred.dev
  - name: mongodb-colordb-cred
    envs:
      - .env.colordb-cred.dev
